# Generated by Django 4.1.5 on 2023-04-17 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.TextField(blank=True, null=True, verbose_name="Parameters"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=25, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Status"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Time"
                    ),
                ),
                ("logs", models.TextField(blank=True, null=True, verbose_name="Logs")),
                (
                    "errors",
                    models.TextField(blank=True, null=True, verbose_name="Errors"),
                ),
                (
                    "project_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.projecttask",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projecttask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.task"
            ),
        ),
    ]
