# Generated by Django 4.1.5 on 2023-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
