# Generated by Django 4.1.5 on 2023-07-17 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_id_alter_projecttask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='first_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='First Created'),
        ),
    ]
